name: Build and test DataSQRL sales agent

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      TZ: 'America/Los_Angeles'

    steps:
    - uses: actions/checkout@v4

    - name: Setup Timezone
      uses: szenius/set-timezone@v1.1
      with:
        timezoneLinux: "America/Los_Angeles"

    - name: Pull SQRL Docker image
      run: docker pull datasqrl/cmd:0.6.0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run sales-agent Tests
      working-directory: ./
      run: |
        echo "Running test command"
        docker run -it --rm -v $PWD:/build datasqrl/cmd:0.6.0 test -c package-test.json --snapshots test-snapshots
